import { expressjwt } from "express-jwt";

import Token from "../models/token";

export const auth = expressjwt({
  secret: process.env.JWT_SECRET,
  algorithms: ["HS256"],
  userProperty: "auth", // this is where the next middleware can find the decoded data generated by jwt-express
  isRevoked,
});

const isRevoked = async (req, jwt) => {
  const authHeader = req.headers.authorization;
  if (!authHeader || !authHeader.startsWith("Bearer ")) {
    return true;
  }
  const accessToken = authHeader.split(" ")[1];
  const token = await Token.findOne({ accessToken });
  if (!token) return true;

  const adminRegex = /^\/api\/v1\/admin\//;
  const adminFault = adminRegex.test(req.originalUrl) && !token.isAdmin; // if the request is for admin and the token is not admin, then revoke the token
  if (adminFault) return true;

  return false;
};
